- hosts: frontends
  gather_facts: false
  tasks:
  - name: Curl website
    uri:
      url: "http://localhost/ping"
      return_content: yes
    until: '"alive" in webpage.content'
    retries: 10
    delay: 1
    register: webpage
        
  - debug: var=webpage.content
