- hosts: workstation
  gather_facts: true
  roles:
  - name: osp-facts

- name: Gather database facts
  hosts: appdbs
  gather_facts: true

  tasks: []


# Setup database tier
- name: Deploy, configure, and populate Postgres 10
  become: yes
  hosts: appdbs
  roles:
    - {name: base-config, tags: base-config}
    - {name: db-tier, tags: [dbs, postgres]}

# Setup application servers tier
- name: Deploy, configure, and populate flask repo and virtualenv
  hosts: apps
  become: yes
  gather_facts: false
  roles:
    - {name: base-config, tags: base-config}
    - {name: app-tier, tags: [apps, flask]}

# Setup front-end load balancer tier
- name: setup load-balancer tier
  hosts: frontends
  become: yes
  roles:
    - {name: base-config, tags: base-config}
    - {name: lb-tier, tags: [lbs, haproxy]}

