---
# Initial, common, system setup steps

- name: enable sudo without tty for some ansible commands
  replace:
    path: /etc/sudoers
    regexp: '^Defaults\s*requiretty'
    replace: 'Defaults  !requiretty'
    backup: yes

- name: enable repos
  blockinfile:
    create: yes
    path: /etc/yum.repos.d/open_three-tier-app.repo
    block: |2
      [rhel-7-server-rpms]
      name=rhel-7-server-rpms
      baseurl=http://d3s3zqyaz8cp2d.cloudfront.net/repos/tower/3.7.0-4/rhel-7-server-rpms
      enabled=1
      gpgcheck=0

      [rhel-7-server-rh-common-rpms]
      name=rhel-7-server-rh-common-rpms
      baseurl=http://d3s3zqyaz8cp2d.cloudfront.net/repos/tower/3.7.0-4/rhel-7-server-rh-common-rpms
      enabled=1
      gpgcheck=0

      [rhel-7-server-extras-rpms]
      name=rhel-7-server-extras-rpms
      baseurl=http://d3s3zqyaz8cp2d.cloudfront.net/repos/tower/3.7.0-4/rhel-7-server-extras-rpms
      enabled=1
      gpgcheck=0

      [rhel-7-server-optional-rpms]
      name=rhel-7-server-optional-rpms
      baseurl=http://d3s3zqyaz8cp2d.cloudfront.net/repos/tower/3.7.0-4/rhel-7-server-optional-rpms
      enabled=1
      gpgcheck=0

      [rhel-server-rhscl-7-rpms]
      name=rhel-server-rhscl-7-rpms
      baseurl=http://d3s3zqyaz8cp2d.cloudfront.net/repos/tower/3.7.0-4/rhel-server-rhscl-7-rpms
      enabled=1
      gpgcheck=0

      [rhel-7-server-ansible-2.9-rpms]
      name=rhel-7-server-ansible-2.9-rpms
      baseurl=http://d3s3zqyaz8cp2d.cloudfront.net/repos/tower/3.7.0-4/rhel-7-server-ansible-2.9-rpms
      enabled=1
      gpgcheck=0

      [epel]
      name=Extra Packages for Enterprise Linux 7
      baseurl=http://d3s3zqyaz8cp2d.cloudfront.net/repos/epel
      enabled=1
      gpgcheck=0

